port: 7900
relative_path: "/admin-panel"

api_path: '/admin-panel'

db:
  database: 'school_core_v3'
  username: 'root'
  password: 'root'
  host: 'localhost'
  port: '3306'
  dialect: 'mysql'

curriculum_db: "school_curriculum_builder_v3"

redis:
  keyPrefix: 'admin'
  maxRetriesPerRequest: 5

rabbitmq:

morgan: ':method :url - userId=:userId schoolId=:schoolId - :response-time ms - :status'

dist: '../client/dist/client'

express-session:
  name: 'connect.sid'
  secret: '0019ee771da34fab96af'
  resave: false
  rolling: true
  saveUninitialized: true
  cookie:
    path: '/'
    secure: false
    maxAge: 600000000

queryBadChars: "['*%–\"\\-]"

connect-redis:

cors:

helmet:

auth:
  check_interval: 5000
  unauthorised:
    url: /api/login
  issuer:
    issuer: 'https://stg-auth.beedtheworld.com'
    authorization_endpoint: 'https://stg-auth.beedtheworld.com/connect/authorize'
    token_endpoint: 'https://stg-auth.beedtheworld.com/connect/token'
    userinfo_endpoint: 'https://stg-auth.beedtheworld.com/connect/userinfo'
    end_session_endpoint: 'https://stg-auth.beedtheworld.com/connect/endsession'
    revocation_endpoint: 'https://stg-auth.beedtheworld.com/connect/revocation'
    introspection_endpoint: 'https://stg-auth.beedtheworld.com/connect/introspect'
    jwks_uri: 'https://stg-auth.beedtheworld.com/.well-known/openid-configuration/jwks'
    change_pass_url: '/account/changepassword'
  client:
    client_id: ''
    client_secret: ''
  request:
    response_type: 'code id_token'
    scope: 'openid offline_access beedos_auth_api'
    response_mode: 'form_post'
  request_login:
    prompt: 'login'
  request_silent:
    prompt: "none"
  http:
    timeout: 10000
  fake: false
  redirect_uri: "api/v1/auth/return"
  post_logout_redirect_uri: "api/v1/auth/logout/done"


reqUserConfig:
  subgroupsMaxCount: 6
  helpEmail: help@beed.world

createStartUser:
  city:
    id: 1
  branch:
    id: '' # optional
    name: '' # unique
  school:
    id: '' # optional
    name: '' # unique
  user:
    email: '' # unique
    name: 'User' # default name
    lastName: 'User' # default last name

synchronizeUsers:
  schoolIds: []

api:
  # casper
  user:
    baseUrl: 'https://test-user.beed.world'
    account: '/api/accounts'
